name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install gf
      run: wget https://github.com/gogf/gf/releases/download/v2.0.6/gf_linux_amd64 -O gf && chmod +x gf &&  ./gf install
    - name: Build
      run: gf build main.go -n main -a amd64,386 -s linux -p .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.REPOSITORY_NAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: registry.cn-hangzhou.aliyuncs.com/daveroey/faas-go:v1.0
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.PORT }}
        script: |-
          docker service update --image registry.cn-hangzhou.aliyuncs.com/daveroey/faas-go:v1.0 --force --no-resolve-image --with-registry-auth  faas_go
